import Foundation

// MARK: - Wire DTOs
//
// Match `backend/pipeline/models.py` (Quant Research Platform pipeline —
// Feature Store -> Technical/Fundamental/News Engines -> Decision Engine),
// `backend/decision_engine/models.py`, and the `/price/{symbol}` and
// `/chart/{symbol}` handlers in `backend/main.py` exactly. Plain camelCase
// property names, no custom `CodingKeys` (see PortfolioModels.swift for why
// mixing in snake_case CodingKeys breaks `APICoding`'s
// `convertFromSnakeCase`).
//
// `/analyze`/`/analyze/enhanced` (the legacy `core.analyzer` scoring path)
// are deliberately NOT used here — that endpoint's own docstring in
// `main.py` states `/quant/analyze` "is the sole canonical production
// decision path for anything that isn't this pinned legacy contract",
// and only `/quant/analyze` actually is the
// Technical/Fundamental/News-Engine -> Decision-Engine architecture this
// screen is required to present.

/// Wire shape of `decision_engine.models.Prediction`.
enum QuantDecision: String, Decodable, Sendable, Equatable {
    case buy = "BUY"
    case hold = "HOLD"
    case sell = "SELL"
}

/// Wire shape of `pipeline.models.EngineExecutionStatus`.
enum EngineExecutionStatus: String, Decodable, Sendable, Equatable {
    case success
    case timeout
    case failed
    case invalid
}

/// Wire shape of `pipeline.models.EngineBreakdownItem` — one voting
/// engine's contribution. `prediction`/`confidence`/`expectedReturn`/
/// `volatility` are `nil` when `status != .success`, exactly as the
/// backend models them — never defaulted to zero.
struct EngineBreakdownItemDTO: Decodable, Sendable {
    let engineName: String
    let engineVersion: String
    let status: EngineExecutionStatus
    let prediction: QuantDecision?
    let confidence: Double?
    let expectedReturn: Double?
    let volatility: Double?
    let evidence: [String]
}

/// Wire shape of `pipeline.models.RiskAssessment`. This is everything the
/// backend currently exposes at the asset (pre-trade) level — no entry
/// price/stop-loss/take-profit/ATR/risk-reward fields exist here (those
/// only exist portfolio-side, via `GET /portfolios/{id}/risk`'s
/// `RiskAnalytics`, a different, position-scoped concept). Not invented.
struct RiskAssessmentDTO: Decodable, Sendable {
    let riskLevel: String
    let expectedVolatility: Double
    let dataSufficiency: Double
}

/// Wire shape of `pipeline.models.PipelineMetadata`. Only the fields this
/// screen needs to show "N/M engines succeeded" — `totalDurationMs`,
/// `stageDurationsMs`, and `timestamp` are ignored (same "only model what
/// this screen needs" call Step 3 made for `Portfolio.created_at`).
struct PipelineMetadataDTO: Decodable, Sendable {
    let pipelineVersion: String
    let enginesAvailable: Int
    let enginesSucceeded: Int
    let degraded: Bool
}

/// Wire shape of `pipeline.models.PipelineResponse` — the `/quant/analyze`
/// response body.
///
/// `explanation: str` is deliberately NOT modeled here. It is backend-
/// generated by `explanation_engine/groq_provider.py` — an LLM call, with
/// a deterministic template fallback only when that call fails (see
/// `explanation_engine/fallback.py`). Step 5's brief explicitly forbids
/// any LLM-authored content on this screen; omitting the field from the
/// DTO makes that a compile-time guarantee rather than a UI convention
/// that could later be violated by accident. The deterministic
/// `evidence: [String]` (built directly by `engines/*/engine.py`, no LLM
/// involved) is what Section 12's "Evidence" requirement actually wants,
/// and is modeled and shown.
struct PipelineResponseDTO: Decodable, Sendable {
    let symbol: String
    let decision: QuantDecision
    let confidence: Double
    let expectedReturn: Double
    let expectedVolatility: Double
    let engineBreakdown: [EngineBreakdownItemDTO]
    let evidence: [String]
    let risk: RiskAssessmentDTO
    let metadata: PipelineMetadataDTO
}

/// Wire shape of the `QuantAnalysisRequest` body `/quant/analyze` expects.
struct QuantAnalysisRequestDTO: Encodable, Sendable {
    let symbol: String
    let assetType: String
}

/// Wire shape of `GET /price/{symbol}`'s response. The backend returns
/// this as an untyped `Dict[str, Any]` (no Pydantic `response_model` on
/// that route), but Step 5 requires explicit `Codable` DTOs regardless —
/// this mirrors the handler's literal return dict field-for-field. No
/// `currency`/`exchange`/`previous_close` field exists here; not invented.
struct PriceQuoteDTO: Decodable, Sendable {
    let symbol: String
    let price: Double
    let changePct: Double
    let timestamp: String
}

/// Wire shape of `models.schemas.ChartPoint`.
struct ChartPointDTO: Decodable, Sendable {
    let date: String
    let close: Double
    let volume: Double
    let rsi: Double?
}

/// Wire shape of `models.schemas.ChartResponse` — the `/chart/{symbol}`
/// response body.
struct ChartResponseDTO: Decodable, Sendable {
    let symbol: String
    let period: String
    let points: [ChartPointDTO]
    let changePct: Double
    let high: Double
    let low: Double
}

// MARK: - Domain models

/// One voting engine's contribution, as actually returned by
/// `/quant/analyze`. `TechnicalEngine`/`FundamentalEngine`/`NewsEngine`
/// are the three named in `pipeline.service.PipelineService`, but the
/// backend can fold in additional active ML model-serving engines too
/// (`PipelineService._resolve_model_serving_engines()`) — `displayName`
/// falls back to the raw `engineName` for anything this screen doesn't
/// specifically recognize, rather than mislabeling it.
struct EngineVoteSummary: Sendable, Equatable, Identifiable {
    var id: String { engineName }
    let engineName: String
    let engineVersion: String
    let status: EngineExecutionStatus
    let prediction: QuantDecision?
    let confidence: Double?
    let expectedReturn: Double?
    let volatility: Double?
    let evidence: [String]

    init(dto: EngineBreakdownItemDTO) {
        engineName = dto.engineName
        engineVersion = dto.engineVersion
        status = dto.status
        prediction = dto.prediction
        confidence = dto.confidence
        expectedReturn = dto.expectedReturn
        volatility = dto.volatility
        evidence = dto.evidence
    }

    var displayName: String {
        switch engineName {
        case "TechnicalEngine": return "Technical"
        case "FundamentalEngine": return "Fundamental"
        case "NewsEngine": return "News"
        default: return engineName
        }
    }
}

struct RiskSummary: Sendable, Equatable {
    let riskLevel: String
    let expectedVolatility: Double
    let dataSufficiency: Double

    init(dto: RiskAssessmentDTO) {
        riskLevel = dto.riskLevel
        expectedVolatility = dto.expectedVolatility
        dataSufficiency = dto.dataSufficiency
    }
}

/// The Decision Engine's aggregated output plus every engine's individual
/// vote, evidence, and risk assessment — everything `/quant/analyze`
/// actually returns (minus the excluded `explanation`, see
/// `PipelineResponseDTO`). This is the type a future AI Analyst would
/// consume as its deterministic input (Step 5's Section 22) — it carries
/// only backend-sourced data, never a locally computed score.
struct QuantAnalysis: Sendable, Equatable {
    let symbol: String
    let decision: QuantDecision
    let confidence: Double
    let expectedReturn: Double
    let expectedVolatility: Double
    let engineVotes: [EngineVoteSummary]
    let evidence: [String]
    let risk: RiskSummary
    let enginesAvailable: Int
    let enginesSucceeded: Int
    let degraded: Bool

    init(dto: PipelineResponseDTO) {
        symbol = dto.symbol
        decision = dto.decision
        confidence = dto.confidence
        expectedReturn = dto.expectedReturn
        expectedVolatility = dto.expectedVolatility
        engineVotes = dto.engineBreakdown.map(EngineVoteSummary.init(dto:))
        evidence = dto.evidence
        risk = RiskSummary(dto: dto.risk)
        enginesAvailable = dto.metadata.enginesAvailable
        enginesSucceeded = dto.metadata.enginesSucceeded
        degraded = dto.metadata.degraded
    }

    private func vote(named engineName: String) -> EngineVoteSummary? {
        engineVotes.first { $0.engineName == engineName }
    }

    var technical: EngineVoteSummary? { vote(named: "TechnicalEngine") }
    var fundamental: EngineVoteSummary? { vote(named: "FundamentalEngine") }
    var news: EngineVoteSummary? { vote(named: "NewsEngine") }

    /// Any engine the backend folded in beyond the three named above —
    /// e.g. an active ML model-serving engine. Shown generically rather
    /// than silently dropped.
    var otherEngines: [EngineVoteSummary] {
        let known: Set<String> = ["TechnicalEngine", "FundamentalEngine", "NewsEngine"]
        return engineVotes.filter { !known.contains($0.engineName) }
    }
}

/// Real-time quote, as actually returned by `GET /price/{symbol}`.
struct MarketQuote: Sendable, Equatable {
    let symbol: String
    let price: Double
    let changePct: Double
    let timestamp: Date?

    init(dto: PriceQuoteDTO) {
        symbol = dto.symbol
        price = dto.price
        changePct = dto.changePct
        timestamp = ISO8601DateFormatter().date(from: dto.timestamp)
    }
}

struct AssetPriceChartPoint: Sendable, Equatable, Identifiable {
    var id: String { date }
    let date: String
    let close: Double
    let volume: Double
    let rsi: Double?
}

/// Historical price series, as actually returned by `GET /chart/{symbol}`.
struct AssetPriceChart: Sendable, Equatable {
    let period: String
    let points: [AssetPriceChartPoint]
    let changePct: Double
    let high: Double
    let low: Double

    init(dto: ChartResponseDTO) {
        period = dto.period
        points = dto.points.map { AssetPriceChartPoint(date: $0.date, close: $0.close, volume: $0.volume, rsi: $0.rsi) }
        changePct = dto.changePct
        high = dto.high
        low = dto.low
    }
}

/// Everything `AssetDetailView` needs to render. `quant` is required —
/// it's the reason this screen exists. `marketData`/`chart` are
/// best-effort enrichments from separate, independent endpoints: `nil`
/// means that endpoint failed or returned nothing, a real and honest
/// state (never backfilled with a guess), not a reason to fail the whole
/// screen when the Quant analysis itself succeeded.
struct AssetDetailSummary: Sendable, Equatable {
    let symbol: String
    let quant: QuantAnalysis
    let marketData: MarketQuote?
    let chart: AssetPriceChart?
}
